apiVersion: onap.org/v1alpha1
kind: CollectdPlugin
metadata:
  name: cpu
spec:
  # Add fields here
  pluginName: "cpu"
  pluginConf: |
    <Plugin "cpu">
      Interval 5
      ReportByState false
      ReportByCpu false
    </Plugin>
 