---
- hosts: vFWDT
  gather_facts: no
  remote_user: ubuntu
  tasks:
  - debug: var="new_software_version"
    failed_when: new_software_version is not defined
  - debug: var="existing_software_version"
    failed_when: existing_software_version is not defined
  - name: Read OLD Software Version
    shell: cat /opt/config/version.txt
    register: old_version
    become: true
  - debug: var=old_version.stdout
    failed_when: old_version.stdout != new_software_version
