# Default values for cadvisor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: default
image:
  repository: google/cadvisor
  tag: latest
  pullPolicy: IfNotPresent
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
cadvisor_prometheus:
  service:
    port: 80
    nodePort: 30091
    targetPort: 8080
    selector:
      app: cadvisor
      collector: cadvisor
