{{- if .Values.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: collectd-operator
  labels:
    app: {{ template "collectd-operator.name" . }}
    chart: {{ template "collectd-operator.chart" . }}
    component: service-account
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}